# 错误和异常

在程序执行过程中，不可避免的会遇到某些错误，如果我们不对这些错误进行处理，那么程序很有可能会因为这个错误而崩溃

## 语法错误

Python的语法错误是`SyntaxError`，通常是由于语法错误造成的，遇到这个错误则需要查看代码中有哪里出现了语法错误

## 异常

即使我们写的程序是没有问题的，但是不保证在运行的时候不出现问题，比如你本来想让用户输入一个数字，用户却输入了一个字母，或者将一个数除以0，这都可能导致运行时错误，大多数异常都不会被程序处理，而是以错误信息被展示出来
```py
>>> 10/0                #0作为除数
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>> "Str"+10            #字符串与数字相加
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can only concatenate str (not "int") to str
>>> int("HelloWorld")   #尝试把一串字母转换成数字
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'HelloWorld'
```

不同的异常会有不同的类型，比如上面的`ZeroDivisionError`,`TypeError`,`ValueError`。错误信息前面会显示引发异常的语句，并以调用栈的形式显示具体信息

## 处理异常

处理异常可以使用`try-except`语句

```py
>>> while True:
...     try:
...         s = input("请输入一个整数：")  
...         num = int(s)
...         print(num)
...     except ValueError as e:
...         print(e)
...         print("请输入整数，而不是其他字符") 
... 
请输入一个整数：x
invalid literal for int() with base 10: 'x'
请输入整数，而不是其他字符
请输入一个整数：2
2
```

同一个`except`子句可以捕获多种错误
```py
>>> while True:
...     try:
...         s = input("请输入一个数字：")
...         num = int(s)
...         print(10/num)
...     except (ValueError,ZeroDivisionError):
...         print("输入数值错误或者数值为0")
...
请输入一个数字：a
输入数值错误或者数值为0
请输入一个数字：0
输入数值错误或者数值为0
请输入一个数字：5
2.0
```
最后一个`except`语句可以省略异常类型，用于匹配所有异常

## else子句

`else`子句将在`try`子句没有发生任何异常的时候执行
```py
>>> while True:
...     try:
...         s = input("请输入一个整数：")
...         print("s =",int(s))
...     except:
...         print("出现错误")
...     else:
...         print("没出现错误")
... 
请输入一个整数：a
出现错误
请输入一个整数：2
s = 2
没出现错误
```

## finally子句

在try-except语句中，可选择使用finally语句，无论是否发生异常，都将执行finally子句中的代码
```py
>>> while True:
...     try:
...         s = input("请输入一个整数：")
...         print("s =",int(s))
...     except:
...         print("出现错误")
...     else:
...         print("没出现错误")
...     finally:
...         print("无论有没有错，都执行")
... 
请输入一个整数：a
出现错误
无论有没有错，都执行
请输入一个整数：3
s = 3
没出现错误
无论有没有错，都执行
```

## 抛出异常

使用`raise`语句来抛出一个异常，格式为:`raise [Exception[,args[,traceback]]]`
```py
>>> n = int(input())
0
>>> if n == 0:
...     raise ValueError("除数不能为0")
... else:
...     print(10/n)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ValueError: 除数不能为0
```

## assert断言

`assert`关键字后应跟一个表达式，当表达式为True时不产生任何效果，当表达式为False的时候将抛出`AssertionError`
```py
>>> assert True 
>>> assert False,"There is a False" 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: There is a False
```

`assert`多用于在代码中加入检查点，启动Python解释器时可以用`-O`参数来关闭`assert`